// Generated by CoffeeScript 1.3.3
(function() {
  var TimeSlot, classes, time;

  classes = [];

  while (classes.length < 7) {
    classes.push([]);
  }

  TimeSlot = (function() {

    function TimeSlot(from, to, title, room) {
      this.from = from;
      this.to = to;
      this.title = title;
      this.room = room;
    }

    return TimeSlot;

  })();

  time = [];

  $(document).ready(function() {
    var c1, c2, day, i, j, _i, _j, _ref;
    $(".ruTable tr").each(function(index, ele) {
      return $(this).children('td').each(function(cindex, cele) {
        if (cindex === 0) {
          time = $(this).html().split('&nbsp;');
        }
        return $(this).children("span").each(function(sindex, sele) {
          var room, span, title;
          span = $(this);
          room = span.text();
          room = room.substring(room.length - 5, room.length - 1);
          title = span.attr("title").split("\n");
          title = title[0] + " - " + title[2];
          return classes[cindex - 1].push(new TimeSlot(time[0], time[1], title, room));
        });
      });
    });
    console.log(classes);
    for (i = _i = 0; _i <= 8; i = ++_i) {
      day = classes[i];
      if (!(day != null)) {
        continue;
      }
      for (j = _j = 1, _ref = day.length; 1 <= _ref ? _j <= _ref : _j >= _ref; j = 1 <= _ref ? ++_j : --_j) {
        c1 = day[j - 1];
        c2 = day[j];
        if ((c1 != null) && (c2 != null) && c1.title === c2.title && c1.room === c2.room) {
          c1.to = c2.to;
          day[j] = null;
          day[j - 1] = c1;
        }
      }
      classes[i] = day;
    }
    return console.log(classes);
  });

}).call(this);
